/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.Cargo_Dao;
import Model.Cargo_Model;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEX DIAS
 */
public class Cargo_View extends javax.swing.JInternalFrame {
    
    Cargo_Model cargo;
    Cargo_Dao cargo_Dao;
    List<Cargo_Model> cargos;
    DefaultTableModel modelo = new DefaultTableModel();
    String user = "";
    String user2;
    
    public Cargo_View() {
         cargo_Dao = new Cargo_Dao();
        initComponents();
        
         this.setVisible(true);
        Campos(false, false);
        
        Campos_Botão(true, false, false, false, false,true,false);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Pesquisar = new javax.swing.JButton();
        Btn_Excluir = new javax.swing.JButton();
        Btn_Limpar = new javax.swing.JButton();
        Btn_Salvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtNomecargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Btn_Novo = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Cargo = new javax.swing.JTable();
        Btn_Alterar = new javax.swing.JButton();
        ButtonSair = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 149, 255));
        setClosable(true);
        setTitle("Cadastro de Cargo");
        setPreferredSize(new java.awt.Dimension(1078, 637));

        Btn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_16px_1.png"))); // NOI18N
        Btn_Pesquisar.setText("Pesquisar");
        Btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PesquisarActionPerformed(evt);
            }
        });

        Btn_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_16px.png"))); // NOI18N
        Btn_Excluir.setText("Excluir");
        Btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExcluirActionPerformed(evt);
            }
        });

        Btn_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_16px_4.png"))); // NOI18N
        Btn_Limpar.setText("Limpar");
        Btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimparActionPerformed(evt);
            }
        });

        Btn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_16px_1.png"))); // NOI18N
        Btn_Salvar.setText("Salvar");
        Btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Cargo:");

        Btn_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_16px.png"))); // NOI18N
        Btn_Novo.setText("Novo");
        Btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NovoActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_2_16px.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Tabela_Cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_CargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Cargo);
        if (Tabela_Cargo.getColumnModel().getColumnCount() > 0) {
            Tabela_Cargo.getColumnModel().getColumn(0).setMinWidth(50);
            Tabela_Cargo.getColumnModel().getColumn(0).setMaxWidth(70);
            Tabela_Cargo.getColumnModel().getColumn(1).setMinWidth(100);
        }

        Btn_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_16px.png"))); // NOI18N
        Btn_Alterar.setText("Alterar");
        Btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlterarActionPerformed(evt);
            }
        });

        ButtonSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_close_window_40px_2.png"))); // NOI18N
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNomecargo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Pesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Pesquisar)))
                    .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void Limpar()
    {
        TxtID.setText(""); 
        TxtNomecargo.setText(""); 
    }
 
 public void Campos(boolean Id, boolean Ncar )
    {
      
        TxtID.setEnabled(Id);
        TxtNomecargo.setEnabled(Ncar);
        
    }
 
 public void Campos_Botão( boolean BtNov,boolean BtLim,boolean BtAlt, boolean BtExc, boolean BtSal, boolean BtPesq, boolean BtCanc)
    {
       
       Btn_Novo.setEnabled(BtNov);
       Btn_Limpar.setEnabled(BtLim);
       Btn_Alterar.setEnabled(BtAlt);
       Btn_Excluir.setEnabled(BtExc);
       Btn_Salvar.setEnabled(BtSal);
       Btn_Pesquisar.setEnabled(BtPesq);
       Btn_Cancelar.setEnabled(BtCanc);
    }
    
    private void Btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PesquisarActionPerformed
        String ID = JOptionPane.showInputDialog("Digite o ID do Cargo: ");
        cargo = new Cargo_Model();
  
        
        try {
            cargo = cargo_Dao.getCargoById(Integer.parseInt(ID));
        } catch (SQLException ex) {
            Logger.getLogger(Cargo_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    if(cargo == null)
    {
         JOptionPane.showMessageDialog(null, "Cargo não encontrado");
    }
               Campos(false, true);          
               Campos_Botão(false, true, true, true, false, false,true);
            
                TxtID.setText(ID);
                TxtNomecargo.setText(cargo.getNomecargo());
                user = cargo.getNomecargo();
    }//GEN-LAST:event_Btn_PesquisarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        Campos(false, false);

        Campos_Botão(true, false, false, false, false,true,false);
        Limpar();
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NovoActionPerformed
        Campos(false, true);
        Campos_Botão(false, false, false, false, true, false, true);
        Limpar();
    }//GEN-LAST:event_Btn_NovoActionPerformed

    private void Btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExcluirActionPerformed
         int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir os Dados!");
            if( i == 0 )
            {
                 try 
                {  
                  cargo_Dao.excluir(Integer.parseInt(TxtID.getText()));
                  atualizarTabela();
                  Limpar();
                  JOptionPane.showMessageDialog(null, "Removido com Sucesso"); 
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERRO!");
                        e.printStackTrace();
                    }
            }
    }//GEN-LAST:event_Btn_ExcluirActionPerformed

    private void Btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimparActionPerformed
       int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Limpar os Dados!");       
               if( i == 0 )
                {
                    Limpar();
                    Campos(false, false);

                    Campos_Botão(true, false, false, false, false, true,true);
                }
    }//GEN-LAST:event_Btn_LimparActionPerformed

    private void Btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalvarActionPerformed
         try {
             if (TxtNomecargo.getText().isEmpty() ){
                    
                 JOptionPane.showMessageDialog(null, "Preencha o campo cargo");
                 TxtNomecargo.requestFocusInWindow();
                } 
                           
             else {           
                 user2 = cargo_Dao.validarNomeCargo(TxtNomecargo.getText());          
                 if (!user.equals(TxtNomecargo.getText()) && user2.equals(TxtNomecargo.getText())) {           
                     JOptionPane.showMessageDialog(null, "Já existe um cargo com este nome");
                            } 
                            
                        else{
                                cargo.setNomecargo(TxtNomecargo.getText());
                                  
                                try {
                                        cargo_Dao.salvar(cargo);
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Cargo_View.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                    JOptionPane.showMessageDialog(null, "Gravado com Sucesso");
                                    atualizarTabela();
                                    Campos(false, false);
        
                                    Campos_Botão(true, false, false, false, false,true,false);
                            }                                   
                        }     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_Btn_SalvarActionPerformed

    private void Tabela_CargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_CargoMouseClicked
        int i = 0;
        Tabela_Cargo.getModel();
        TxtID.setText(modelo.getValueAt(Tabela_Cargo.getSelectedRow(), 0).toString());
        try {
             Campos(false, true);        
             Campos_Botão(false, true, true, true, false, true,true);
            
             cargo = cargo_Dao.getCargoById(Integer.parseInt(TxtID.getText()));
            
                TxtNomecargo.setText(cargo.getNomecargo());
             
                user = cargo.getNomecargo();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Tabela_CargoMouseClicked

    private void Btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlterarActionPerformed
         try {
             if (TxtNomecargo.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            TxtNomecargo.requestFocusInWindow();
                } 

             else {
                            user2 = cargo_Dao.validarNomeCargo(TxtNomecargo.getText());
                            if (!user.equals(TxtNomecargo.getText()) && user2.equals(TxtNomecargo.getText())) {
                                JOptionPane.showMessageDialog(null, "Já existe um funcionario com este nome");
                            }  else {
                                
//                                
                                cargo.setID(Integer.parseInt(TxtID.getText()));
                                cargo.setNomecargo(TxtNomecargo.getText());

                                int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Alterar os Dados!");   
                                if( i == 0 )
                                { 
                                cargo_Dao.alterar(cargo);
                                
                                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
                                atualizarTabela();
                                Limpar(); 
                                }
                            }
                        }
          
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_Btn_AlterarActionPerformed

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair?") == 0)
        {
            this.dispose();
        }
    }//GEN-LAST:event_ButtonSairActionPerformed

     public void atualizarTabela() {
        cargo = new Cargo_Model();
        try {
            cargos = cargo_Dao.todosCargos();
            String dados[][] = new String[cargos.size()][2];
            int i = 0;
            for (Cargo_Model u : cargos) {
                dados[i][0] = String.valueOf(u.getID());
                dados[i][1] = u.getNomecargo();
                 
                i++;
            }
            String tituloColuna[] = {"ID", "Cargo"};
            modelo.setDataVector(dados, tituloColuna);
            Tabela_Cargo.setModel(modelo);
            Tabela_Cargo.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }    
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Alterar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Excluir;
    private javax.swing.JButton Btn_Limpar;
    private javax.swing.JButton Btn_Novo;
    private javax.swing.JButton Btn_Pesquisar;
    private javax.swing.JButton Btn_Salvar;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JTable Tabela_Cargo;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtNomecargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
