/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.Dao_CadastroFornecedores;
import Model.Fornecedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEX DIAS
 */
public class Fornecedores_View extends javax.swing.JInternalFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Fornecedor> fornecedores;
    Dao_CadastroFornecedores daoFornecedo;
    Fornecedor f;
    public Fornecedores_View() {
        f = new Fornecedor();
        daoFornecedo = new Dao_CadastroFornecedores();
        fornecedores = new ArrayList<>();
        initComponents();
        atualizarTabela();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txRazao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txCNPJ_CPF = new javax.swing.JTextField();
        txInscricao_RG = new javax.swing.JTextField();
        txNomeFantasia = new javax.swing.JTextField();
        btnovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        ButtonSalvarAlterar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txCep = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txComplemento = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txcidade = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txTelefone2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txBanco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txConta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txAgencia = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabCadastro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txNomePes = new javax.swing.JTextField();
        txCodigoPes = new javax.swing.JTextField();
        btpesquisaNome = new javax.swing.JButton();
        btPesquisaCod = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setTitle("Cadastro de Fornecedores");

        jPanel2.setBackground(new java.awt.Color(82, 203, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(82, 203, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Código");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Razão ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nome/N.Fantasia ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("CNPJ ou CPF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Inscrição Estadual ou RG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txInscricao_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(txCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txInscricao_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 992, -1));

        btnovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_16px.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 312, -1, -1));

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_16px_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 312, -1, -1));

        ButtonSalvarAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButtonSalvarAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_16px_1.png"))); // NOI18N
        ButtonSalvarAlterar.setText("Alterar");
        ButtonSalvarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSalvarAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 312, 107, -1));

        jPanel5.setBackground(new java.awt.Color(82, 203, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nome da Rua");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Bairro");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Estado");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nº");

        txCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCepActionPerformed(evt);
            }
        });

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("CEP");

        txNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumeroActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Complemento");

        txComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txComplementoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Cidade");

        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txRua, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 992, -1));

        jPanel6.setBackground(new java.awt.Color(82, 203, 248));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel6.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Telefone");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 30, 60, 20);
        jPanel6.add(txTelefone);
        txTelefone.setBounds(70, 30, 140, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("2º Telefone");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(220, 30, 70, 20);

        txTelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefone2ActionPerformed(evt);
            }
        });
        jPanel6.add(txTelefone2);
        txTelefone2.setBounds(300, 30, 140, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("E-mail");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(470, 30, 40, 20);

        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });
        jPanel6.add(txEmail);
        txEmail.setBounds(510, 30, 430, 20);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 992, 68));

        jPanel7.setBackground(new java.awt.Color(82, 203, 248));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Bancarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Nome do Banco");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(10, 30, 110, 20);
        jPanel7.add(txBanco);
        txBanco.setBounds(110, 30, 350, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Nº da Agência");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(480, 30, 90, 20);

        txConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txContaActionPerformed(evt);
            }
        });
        jPanel7.add(txConta);
        txConta.setBounds(780, 30, 160, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Nº da Conta");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(700, 30, 70, 20);

        txAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAgenciaActionPerformed(evt);
            }
        });
        jPanel7.add(txAgencia);
        txAgencia.setBounds(570, 30, 120, 20);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, 992, 65));

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_16px_4.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 312, -1, -1));

        btAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_16px.png"))); // NOI18N
        btAlterar.setText("Editar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 312, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, 20));

        JTabCadastro.setBackground(new java.awt.Color(82, 203, 248));
        JTabCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão Social", "Nome Fantasia", "CNPJ_CPF", "Inscrição Estadual_RG"
            }
        ));
        JTabCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTabCadastro);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 343, 992, 180));

        jPanel1.setBackground(new java.awt.Color(82, 203, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nome");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Código");

        txNomePes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomePesActionPerformed(evt);
            }
        });

        txCodigoPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoPesActionPerformed(evt);
            }
        });

        btpesquisaNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btpesquisaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_16px_1.png"))); // NOI18N
        btpesquisaNome.setText("Buscar");
        btpesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisaNomeActionPerformed(evt);
            }
        });

        btPesquisaCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btPesquisaCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_16px_1.png"))); // NOI18N
        btPesquisaCod.setText("Buscar");
        btPesquisaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNomePes, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCodigoPes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txNomePes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btpesquisaNome)
                    .addComponent(txCodigoPes)
                    .addComponent(btPesquisaCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 550, 1000, -1));

        btSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_close_window_40px_2.png"))); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel2.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void limpar(){
        txCodigo.setText("");
        txRazao.setText("");
        txCNPJ_CPF.setText("");
        txInscricao_RG.setText("");
        txNomeFantasia.setText("");
        txRua.setText("");
        txNumero.setText("");
        txComplemento.setText("");
        txBairro.setText("");
        txcidade.setText("");
        cbEstado.setSelectedIndex(0);
        txCep.setText("");
        txBanco.setText("");
        txAgencia.setText("");
        txConta.setText("");
        txTelefone.setText("");
        txTelefone2.setText("");
        txEmail.setText("");
        inicio();
    }
    public void CampoTexto(boolean codigo, boolean razao, boolean cnpj, boolean Rg, boolean nomefan, boolean rua, boolean numero, boolean bairro,
            boolean complemento, boolean cidade , boolean estado, boolean cep,  boolean banco, boolean agencia, boolean conta, boolean telefone,boolean telefone2,
            boolean email){
        this.txCodigo.setEnabled(codigo);
        this.txRazao.setEnabled(razao);
        this.txCNPJ_CPF.setEnabled(cnpj);
        this.txInscricao_RG.setEnabled(Rg);
        this.txNomeFantasia.setEnabled(nomefan);
        this.txRua.setEnabled(rua);
        this.txNumero.setEnabled(numero);
        this.txComplemento.setEnabled(complemento);
        this.txBairro.setEnabled(bairro);
        this.txcidade.setEnabled(cidade);
        this.cbEstado.setEnabled(estado);
        this.txCep.setEnabled(cep);
        this.txBanco.setEnabled(banco);
        this.txAgencia.setEnabled(agencia);
        this.txConta.setEnabled(conta);
        this.txTelefone.setEnabled(telefone);
        this.txTelefone2.setEnabled(telefone2);
        this.txEmail.setEnabled(email);
    }
     private void botao(boolean novo, boolean salvar, boolean limpar, boolean sair, 
            boolean salvarAterar, boolean pesCodigo, boolean pesNome, boolean alterar){
        btnovo.setEnabled(novo);
        btSalvar.setEnabled(salvar);
        btLimpar.setEnabled(limpar);
        btSair.setEnabled(sair);
        ButtonSalvarAlterar.setEnabled(salvarAterar);
        btPesquisaCod.setEnabled(pesCodigo);
        btpesquisaNome.setEnabled(pesNome);
        btAlterar.setEnabled(alterar); 
    }
    private void inicio(){
    CampoTexto(false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false);
    botao(true, false, false, true, false, true, true,false);
    }
    
    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        limpar();
        botao(false, true, true, true, false, true, true, false);
        CampoTexto(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true,true);
    }//GEN-LAST:event_btnovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        boolean CV = camposVazios();
        if(CV){
            f = new Fornecedor();

            f.setRazao(txRazao.getText());
            f.setNomeFantasia(txNomeFantasia.getText());
            f.setCnpj_cpf(txCNPJ_CPF.getText());
            f.setInscricaoEstadual_RG(txInscricao_RG.getText());
            f.setRua(txRua.getText());
            f.setNumero(txNumero.getText());
            f.setComplemento(txComplemento.getText());
            f.setBairro(txBairro.getText());
            f.setCidade(txcidade.getText());
            f.setEstado((String) cbEstado.getSelectedItem());
            f.setCep(txCep.getText());
            f.setBanco(txBanco.getText());
            f.setAgencia(txAgencia.getText());
            f.setConta(txConta.getText());
            f.setTelefone1(txTelefone.getText());
            f.setTelefone2(txTelefone2.getText());
            f.setEmail(txEmail.getText());

                try {
                    daoFornecedo.salvar(f);
                } catch (SQLException ex) {
                    Logger.getLogger(Fornecedores_View.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            JOptionPane.showMessageDialog(null, "SALVO");
            atualizarTabela();
            limpar();
        }else{
            JOptionPane.showMessageDialog(null, "A campos a serem preenchidos");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void ButtonSalvarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarAlterarActionPerformed
        int o = JOptionPane.showConfirmDialog(null, "Você Quer Alterar os Dados Cadastrados");
        if (o == 0) {
            boolean v = camposVazios();
            if (v) {
                f.setRazao(txRazao.getText());
                f.setNomeFantasia(txNomeFantasia.getText());
                f.setCnpj_cpf(txCNPJ_CPF.getText());
                f.setInscricaoEstadual_RG(txInscricao_RG.getText());
                f.setRua(txRua.getText());
                f.setNumero(txNumero.getText());
                f.setComplemento(txComplemento.getText());
                f.setBairro(txBairro.getText());
                f.setCidade(txcidade.getText());
                f.setEstado((String) cbEstado.getSelectedItem());
                f.setCep(txCep.getText());
                f.setBanco(txBanco.getText());
                f.setAgencia(txAgencia.getText());
                f.setConta(txConta.getText());
                f.setTelefone1(txTelefone.getText());
                f.setTelefone2(txTelefone2.getText());
                f.setEmail(txEmail.getText());

                    try {
                        daoFornecedo.getAlterar(f);
                    } catch (SQLException ex) {
                        Logger.getLogger(Fornecedores_View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                JOptionPane.showMessageDialog(null, "ALTERADO");
                atualizarTabela();
                limpar();
            }
        }
    }//GEN-LAST:event_ButtonSalvarAlterarActionPerformed

    private void txCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCepActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void txNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumeroActionPerformed

    private void txComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txComplementoActionPerformed

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void txTelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefone2ActionPerformed

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailActionPerformed

    private void txContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txContaActionPerformed

    private void txAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAgenciaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if(txCodigoPes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Escolha um para Alterar");
        }
        else{

            CampoTexto(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true,true);
            botao(false, false, true, true, true, true, true, false);
            txCodigoPes.setText("");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarTabela();
        txCodigoPes.setText("");
        btAlterar.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTabCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabCadastroMouseClicked
        if (JTabCadastro.getSelectedRow() != -1) {
            int a = Integer.valueOf(JTabCadastro.getValueAt(JTabCadastro.getSelectedRow(), 0).toString());
            txCodigoPes.setText(JTabCadastro.getValueAt(JTabCadastro.getSelectedRow(), 0).toString());
            try{

                f = daoFornecedo.getUsuarioByCodigo(a);
                txCodigo.setText(String.valueOf(f.getCodigo()));
                txRazao.setText(f.getRazao());
                txCNPJ_CPF.setText(f.getCnpj_cpf());
                txInscricao_RG.setText(f.getInscricaoEstadual_RG());
                txNomeFantasia.setText(f.getNomeFantasia());
                txRua.setText(f.getRua());
                txBairro.setText(f.getBairro());
                txNumero.setText((f.getNumero()));
                txComplemento.setText(f.getComplemento());
                txcidade.setText(f.getCidade());
                txCep.setText(f.getCep());
                cbEstado.setSelectedItem(f.getEstado());
                txBanco.setText(f.getBanco());
                txAgencia.setText(f.getAgencia());
                txConta.setText(f.getConta());
                txTelefone.setText(f.getTelefone1());
                txTelefone2.setText(f.getTelefone2());
                txEmail.setText(f.getEmail());

                //               botao(true,false,true,true,true,true,false,true);
                //               campo(true,false,false,false,false,false,false,false);
            }catch(Exception ex){
                ex.printStackTrace();
            }
            btAlterar.setEnabled(true);
        }

    }//GEN-LAST:event_JTabCadastroMouseClicked

    private void txNomePesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomePesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomePesActionPerformed

    private void txCodigoPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoPesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoPesActionPerformed

    private void btpesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisaNomeActionPerformed
        if(txNomePes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite o que esta procurando");
        }else{
            BuscaTabela();
        }
    }//GEN-LAST:event_btpesquisaNomeActionPerformed

    private void btPesquisaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaCodActionPerformed
        if(txCodigoPes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Escolha um codigo");
        }
        else{
            try{
                f = daoFornecedo.getUsuarioByCodigo(Integer.parseInt(txCodigoPes.getText()));
                if(f == null){
                    JOptionPane.showMessageDialog(null, "Usuario não encontrado");
                }
                else{
                    txCodigo.setText(String.valueOf(f.getCodigo()));
                    txRazao.setText(f.getRazao());
                    txCNPJ_CPF.setText(f.getCnpj_cpf());
                    txInscricao_RG.setText(f.getInscricaoEstadual_RG());
                    txNomeFantasia.setText(f.getNomeFantasia());
                    txRua.setText(f.getRua());
                    txBairro.setText(f.getBairro());
                    txNumero.setText((f.getNumero()));
                    txComplemento.setText(f.getComplemento());
                    txcidade.setText(f.getCidade());
                    txCep.setText(f.getCep());
                    cbEstado.setSelectedItem(f.getEstado());
                    txBanco.setText(f.getBanco());
                    txAgencia.setText(f.getAgencia());
                    txConta.setText(f.getConta());
                    txTelefone.setText(f.getTelefone1());
                    txTelefone2.setText(f.getTelefone2());
                    txEmail.setText(f.getEmail());
                    BuscaCodigo();

                    //               botao(true,false,true,true,true,true,false,true);
                    //               campo(true,false,false,false,false,false,false,false);
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
            btAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisaCodActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair?") == 0)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btSairActionPerformed

    private boolean camposVazios(){
         if(txRazao.getText().isEmpty()
            || txCNPJ_CPF.getText().isEmpty()
            || txNomeFantasia.getText().isEmpty()
            || txInscricao_RG.getText().isEmpty() 
            || txRua.getText().isEmpty()||txNumero.getText().isEmpty()
            ||txBairro.getText().isEmpty()||txcidade.getText().isEmpty()
            ||cbEstado.getSelectedItem().equals(" ")){
             return false;
         }else{
             return true;
         }
    }
    
    public void atualizarTabela(){
      f = new Fornecedor();
        try {
           fornecedores = (ArrayList<Fornecedor>) daoFornecedo.todosUsuarios();
            String dados[][] = new String[fornecedores.size()][5];
            int i = 0;
            for (Fornecedor f : fornecedores) {
                
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getNomeFantasia();
                dados[i][2] = f.getCnpj_cpf();
                dados[i][3] = f.getInscricaoEstadual_RG();
                dados[i][4] = f.getTelefone1();
                i++;
            }
            modeloDATabela(dados);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void BuscaCodigo(){
        f = new Fornecedor();
        try {
            f = daoFornecedo.getUsuarioByCodigo(Integer.valueOf(txCodigoPes.getText()));
            String dados[][] = new String[1][5];
            int i = 0;
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getNomeFantasia();
                dados[i][2] = f.getCnpj_cpf();
                dados[i][3] = f.getInscricaoEstadual_RG();
                dados[i][4] = f.getTelefone1();
            
            modeloDATabela(dados);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
        //---------------------Fomataçao das tabelas--------------------------
    String tituloColuna[] = {"Codigo", "Nome", "CNPJ/CPF","Inscrião/RG", "Telefone"};
    public void modeloDATabela(String[][] a){
            modelo.setDataVector(a, tituloColuna);
            JTabCadastro.setModel(new DefaultTableModel(a,tituloColuna){
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
            });
            JTabCadastro.getColumnModel().getColumn(0).setPreferredWidth(30);
            JTabCadastro.getColumnModel().getColumn(1).setPreferredWidth(200);
            JTabCadastro.getColumnModel().getColumn(2).setPreferredWidth(100);
            JTabCadastro.getColumnModel().getColumn(3).setPreferredWidth(100);
            JTabCadastro.getColumnModel().getColumn(4).setPreferredWidth(100);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);            
            JTabCadastro.getColumnModel().getColumn(0).setCellRenderer(centralizado);            
            JTabCadastro.setRowHeight(25);               
    }
    //---------------------------------------------------------------------
     
     private void BuscaTabela(){
        f = new Fornecedor();
        try {
            fornecedores = (ArrayList<Fornecedor>) daoFornecedo.BuscaUsuarios(txNomePes.getText());
            String dados[][] = new String[fornecedores.size()][8];
            int i = 0;
            for (Fornecedor f : fornecedores) {
                
                dados[i][0] = String.valueOf(f.getCodigo());
                dados[i][1] = f.getNomeFantasia();
                dados[i][2] = f.getCnpj_cpf();
                dados[i][3] = f.getInscricaoEstadual_RG();
                dados[i][4] = f.getTelefone1();
                i++;
            }
            modeloDATabela(dados);
            JTabCadastro.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvarAlterar;
    private javax.swing.JTable JTabCadastro;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisaCod;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btpesquisaNome;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txAgencia;
    private javax.swing.JTextField txBairro;
    private javax.swing.JTextField txBanco;
    private javax.swing.JTextField txCNPJ_CPF;
    private javax.swing.JTextField txCep;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txCodigoPes;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JTextField txConta;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txInscricao_RG;
    private javax.swing.JTextField txNomeFantasia;
    private javax.swing.JTextField txNomePes;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txRazao;
    private javax.swing.JTextField txRua;
    private javax.swing.JTextField txTelefone;
    private javax.swing.JTextField txTelefone2;
    private javax.swing.JTextField txcidade;
    // End of variables declaration//GEN-END:variables
}
