/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ClienteFisico_dao;
import Model.ClienteFisico;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PessoaFisica extends javax.swing.JInternalFrame {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
    ClienteFisico fis;
    ClienteFisico_dao fis_dao;
    List <ClienteFisico> fisicos;
    DefaultTableModel modelo = new DefaultTableModel();
    public PessoaFisica() {
        fis_dao = new ClienteFisico_dao();
        
        
        initComponents();
        iniciar();
        Limpar();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFisica = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtApelido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxCPF = new javax.swing.JTextField();
        TxRG = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cbStatusFis = new javax.swing.JComboBox<>();
        txData = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtRua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtCidade = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxCEP = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TxtComplemento = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtTelefone1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtCelular = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonPesquisarid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Funcionario = new javax.swing.JTable();
        ButtonSair = new javax.swing.JButton();

        setBackground(new java.awt.Color(113, 207, 231));
        setClosable(true);
        setTitle("Pessoa Fisica");

        jPFisica.setBackground(new java.awt.Color(28, 203, 248));
        jPFisica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pessoa Física", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Small", 1, 11))); // NOI18N
        jPFisica.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel2.setText("ID:");
        jPFisica.add(jLabel2);
        jLabel2.setBounds(10, 20, 30, 20);
        jPFisica.add(TxtID);
        TxtID.setBounds(30, 20, 40, 20);

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel3.setText("Matrícula:");
        jPFisica.add(jLabel3);
        jLabel3.setBounds(90, 20, 60, 20);
        jPFisica.add(TxtMatricula);
        TxtMatricula.setBounds(150, 20, 110, 20);

        jLabel4.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel4.setText("Apelido:");
        jPFisica.add(jLabel4);
        jLabel4.setBounds(640, 20, 50, 20);
        jPFisica.add(TxtApelido);
        TxtApelido.setBounds(690, 20, 140, 20);

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel5.setText("Estado Civil:");
        jPFisica.add(jLabel5);
        jLabel5.setBounds(10, 60, 80, 20);

        cbEstadoCivil.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casado", "Solteiro" }));
        jPFisica.add(cbEstadoCivil);
        cbEstadoCivil.setBounds(90, 60, 170, 20);

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel6.setText("Dt de Nasc:");
        jPFisica.add(jLabel6);
        jLabel6.setBounds(840, 20, 70, 20);

        jLabel10.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel10.setText("Sexo:");
        jPFisica.add(jLabel10);
        jLabel10.setBounds(650, 60, 40, 20);

        cbSexo.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        jPFisica.add(cbSexo);
        cbSexo.setBounds(690, 60, 140, 20);

        jLabel19.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel19.setText("CPF:");
        jPFisica.add(jLabel19);
        jLabel19.setBounds(270, 60, 30, 14);

        jLabel20.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel20.setText("RG:");
        jPFisica.add(jLabel20);
        jLabel20.setBounds(470, 60, 30, 20);
        jPFisica.add(TxCPF);
        TxCPF.setBounds(310, 60, 150, 20);
        jPFisica.add(TxRG);
        TxRG.setBounds(500, 60, 130, 20);

        jLabel21.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel21.setText("Nome:");
        jPFisica.add(jLabel21);
        jLabel21.setBounds(270, 20, 40, 20);
        jPFisica.add(TxNome);
        TxNome.setBounds(310, 20, 320, 20);

        jLabel29.setText("Status:");
        jPFisica.add(jLabel29);
        jLabel29.setBounds(840, 60, 40, 14);

        cbStatusFis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Nao Ativo" }));
        jPFisica.add(cbStatusFis);
        cbStatusFis.setBounds(910, 60, 90, 20);

        try {
            txData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPFisica.add(txData);
        txData.setBounds(910, 20, 90, 20);

        jPanel2.setBackground(new java.awt.Color(28, 203, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Small", 1, 11))); // NOI18N
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel11.setText("Bairro:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 20, 38, 20);

        TxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBairroActionPerformed(evt);
            }
        });
        jPanel2.add(TxtBairro);
        TxtBairro.setBounds(70, 20, 240, 20);

        jLabel12.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel12.setText("Rua:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(330, 20, 30, 20);
        jPanel2.add(TxtRua);
        TxtRua.setBounds(370, 20, 400, 20);

        jLabel13.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel13.setText("Número:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(850, 20, 50, 20);
        jPanel2.add(TxtNumero);
        TxtNumero.setBounds(910, 20, 90, 20);

        jLabel14.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel14.setText("Cidade:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 50, 50, 20);
        jPanel2.add(TxtCidade);
        TxtCidade.setBounds(70, 50, 240, 20);

        jLabel15.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel15.setText("CEP:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(600, 50, 30, 20);

        try {
            TxCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(TxCEP);
        TxCEP.setBounds(650, 50, 120, 20);

        jLabel16.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel16.setText("Estado:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(320, 50, 50, 20);

        jLabel17.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel17.setText("Complemento:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(790, 50, 90, 20);
        jPanel2.add(TxtComplemento);
        TxtComplemento.setBounds(890, 50, 110, 20);

        TxtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel2.add(TxtEstado);
        TxtEstado.setBounds(370, 50, 190, 20);

        jPanel3.setBackground(new java.awt.Color(28, 203, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel8.setText("Telefone:");

        try {
            TxtTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jLabel9.setText("Celular:");

        try {
            TxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCelularActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jLabel18.setText("E-mail:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(27, 27, 27)
                .addComponent(txEmail)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_16px_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_2_16px.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_16px_4.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_16px.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_16px.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_16px.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pessoa Fisica ID");

        jButtonPesquisarid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPesquisarid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_16px_1.png"))); // NOI18N
        jButtonPesquisarid.setText("Pesquisar");
        jButtonPesquisarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaridActionPerformed(evt);
            }
        });

        Tabela_Funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matricula", "Nome", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_FuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Funcionario);

        ButtonSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_close_window_40px_2.png"))); // NOI18N
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jPFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonPesquisarid)
                    .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void Limpar()
    {
        TxtID.setText(""); 
        cbStatusFis.setSelectedIndex(0);  
        TxtMatricula.setText("");
        TxNome.setText("");
        TxtApelido.setText("");
        cbEstadoCivil.setSelectedIndex(0);
        TxCPF.setText("");
        TxRG.setText("");
        cbSexo.setSelectedIndex(0);
        TxtCelular.setText("");
        txEmail.setText("");
        TxtBairro.setText("");
        TxtRua.setText("");
        TxtNumero.setText("");
        TxtCidade.setText("");
        TxCEP.setText("");
        TxtEstado.setSelectedIndex(0);
        TxtComplemento.setText("");
        TxtTelefone1.setText("");
        txData.setText("");
    }
        public void Campos(boolean Id,boolean status, boolean Mat, boolean NomFan, boolean cnpj, boolean razao, boolean inscricao,boolean Tel, boolean Cel, boolean Emai,boolean Bair, boolean Rua, boolean Num,
         boolean Cid, boolean Cep, boolean Est, boolean Comp,boolean a , boolean b, boolean c, boolean d)
    {      
        TxtID.setEnabled(Id);
        cbStatusFis.setEnabled(status);
        TxtMatricula.setEnabled(Mat);
        TxNome.setEnabled(NomFan);
        TxtApelido.setEnabled(cnpj);
        TxCPF.setEnabled(razao);
        TxRG.setEnabled(inscricao);
        txData.setEnabled(a);
        cbEstadoCivil.setEnabled(status);
        cbSexo.setEnabled(c);
        TxtTelefone1.setEnabled(Tel);
        cbSexo.setEnabled(a);
        TxtCelular.setEnabled(Cel);
        txEmail.setEnabled(Emai);
        TxtBairro.setEnabled(Bair);
        TxtRua.setEnabled(Rua);
        TxtNumero.setEnabled(Num);
        TxtCidade.setEnabled(Cid);
        TxCEP.setEnabled(Cep);
        TxtEstado.setEnabled(Est);
        TxtComplemento.setEnabled(Comp);
    }
     public void Botão( boolean BtNov,boolean BtLim,boolean BtAlt, boolean BtExc, boolean BtSal, boolean BtPesq, boolean BtCanc)
    {
       btNovo.setEnabled(BtNov);
       btLimpar.setEnabled(BtLim);
       btAlterar.setEnabled(BtAlt);
       btExcluir.setEnabled(BtExc);
       btSalvar.setEnabled(BtSal);
       jButtonPesquisarid.setEnabled(BtPesq);
       btCancelar.setEnabled(BtCanc);
    }
   private void iniciar(){
      Campos(false, false, false,false,false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
      Botão(true, false, false, false, false, true, false);
   }
     public boolean verificaCampo(){
        if(cbStatusFis.getSelectedItem().equals("Selecione")||
            TxtMatricula.getText().isEmpty()||TxCPF.getText().isEmpty()||
            TxRG.getText().isEmpty()||TxNome.getText().isEmpty()||
            cbSexo.getSelectedItem().equals("Selecione")|| TxtTelefone1.getText().isEmpty() ||
            TxtCelular.getText().isEmpty() || txEmail.getText().isEmpty() ||
            TxtBairro.getText().isEmpty() || TxtNumero.getText().isEmpty() ||
            TxtRua.getText().isEmpty() || TxtCidade.getText().isEmpty())
        {
            return false;
        }else{
            return true;
        }
     }
          
    private void TxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBairroActionPerformed

    private void TxtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCelularActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
          boolean a = verificaCampo();
                if(a){
                    fis= new ClienteFisico();
                    fis.setStatus((String) cbStatusFis.getSelectedItem());
                    fis.setMatricula(TxtMatricula.getText());
                    fis.setNome(TxNome.getText());
                    fis.setApelido(TxtApelido.getText());
                    fis.setEstadoCivil((String) cbEstadoCivil.getSelectedItem());
                    fis.setCPF(TxCPF.getText());
                    fis.setRG(TxRG.getText());
                    fis.setSexo((String) cbSexo.getSelectedItem());
                  try {
                      fis.setDtNasc(sdf.parse(txData.getText()));
                  } catch (ParseException ex) {
                      Logger.getLogger(PessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
                  }
                    fis.setTelefone(TxtTelefone1.getText());
                    fis.setCelular(TxtCelular.getText());
                    fis.setEmail(txEmail.getText());
                    fis.setBairro(TxtBairro.getText());
                    fis.setRua(TxtRua.getText());
                    fis.setNumero(TxtNumero.getText());
                    fis.setCidade(TxtCidade.getText());
                    fis.setCep(TxCEP.getText());
                    fis.setEstado((String) TxtEstado.getSelectedItem());
                    fis.setComplemento(TxtComplemento.getText());
                  try {
                      fis_dao.salvar(fis);
                      iniciar();
                      Limpar();
                      atualizarTabela();
                      JOptionPane.showMessageDialog(null, "Salvo!");
                  } catch (SQLException ex) {
                      Logger.getLogger(PessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
                  }
                }else{
                  JOptionPane.showMessageDialog(null,"Preencha todos os campos");
                }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        iniciar();
        Limpar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
       int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Limpar os Dados!");       
       if( i == 0 )
        {
            Limpar();
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir os Dados!");
        if( i == 0 ){
                try
                {
                    fis_dao.excluir(Integer.parseInt(TxtID.getText()));
                    Limpar();
                    iniciar();
                    atualizarTabela();
                    JOptionPane.showMessageDialog(null, "Removido com Sucesso");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERRO!");
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed

                if(cbStatusFis.getSelectedItem().equals("Selecione")|| TxtMatricula.getText().isEmpty()||TxCPF.getText().isEmpty()||
                    TxRG.getText().isEmpty()||TxNome.getText().isEmpty()||cbSexo.getSelectedItem().equals("Selecione")|| TxtTelefone1.getText().isEmpty() ||
                    TxtCelular.getText().isEmpty() || txEmail.getText().isEmpty() || TxtBairro.getText().isEmpty() || TxtNumero.getText().isEmpty() ||TxtRua.getText().isEmpty() || TxtCidade.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "A campos a serem preenchidos");
                }else{
                    fis= new ClienteFisico();
                    fis.setId(Integer.parseInt(TxtID.getText()));
                    fis.setStatus((String) cbStatusFis.getSelectedItem());
                    fis.setMatricula(TxtMatricula.getText());
                    fis.setNome(TxNome.getText());
                    fis.setApelido(TxtApelido.getText());
                    fis.setEstadoCivil((String) cbEstadoCivil.getSelectedItem());
                    fis.setCPF(TxCPF.getText());
                    fis.setRG(TxRG.getText());
                    fis.setSexo((String) cbSexo.getSelectedItem());
                    
                    try {
                        fis.setDtNasc(sdf.parse(txData.getText()));
                    } catch (ParseException ex) {
                        Logger.getLogger(PessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
                    }


                    fis.setTelefone(TxtTelefone1.getText());
                    fis.setCelular(TxtCelular.getText());
                    fis.setEmail(txEmail.getText());
                    fis.setBairro(TxtBairro.getText());
                    fis.setRua(TxtRua.getText());
                    fis.setNumero(TxtNumero.getText());
                    fis.setCidade(TxtCidade.getText());
                    fis.setCep(TxCEP.getText());
                    fis.setEstado((String) TxtEstado.getSelectedItem());
                    fis.setComplemento(TxtComplemento.getText());
                    int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Alterar os Dados!");
                    if( i == 0 )
                    {

                        try {
                            fis_dao.alterar(fis);
                        } catch (SQLException ex) {
                            Logger.getLogger(PessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            Limpar();
                            iniciar();
                            atualizarTabela();
                            JOptionPane.showMessageDialog(null, "Salvo!");

                    }
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        Campos(false,true, true, true,true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
        Botão(false, true, false, false, true,false, true);
        Limpar();
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButtonPesquisaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaridActionPerformed
        String ID = JOptionPane.showInputDialog("Digite o ID do Cliente Fisico: ");
        fis = new ClienteFisico();
        jPFisica.setVisible(true);

        try {
            fis = fis_dao.buscaFicicaID(Integer.parseInt(ID));
        } catch (SQLException ex) {
            Logger.getLogger(PessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(fis == null)
        {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        }
        Campos(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true, true, true);
        Botão(false, true, true, true, false, true, true);
        TxtID.setText(ID);
        TxtMatricula.setText(fis.getMatricula());
        TxNome.setText(fis.getNome());
        cbStatusFis.setSelectedItem(fis.getStatus());
        TxtApelido.setText(fis.getApelido());
        cbEstadoCivil.setSelectedItem(fis.getEstadoCivil());
        txData.setText(sdf.format(fis.getDtNasc()));
        cbSexo.setSelectedItem(fis.getSexo());
        TxCPF.setText(fis.getCPF());
        TxRG.setText(fis.getRG());
        TxtTelefone1.setText(fis.getTelefone());
        TxtCelular.setText(fis.getCelular());
        txEmail.setText(fis.getEmail());
        TxtBairro.setText(fis.getBairro());
        TxtRua.setText(fis.getRua());
        TxtNumero.setText(fis.getNumero());
        TxtCidade.setText(fis.getCidade());
        TxCEP.setText(fis.getCep());
        TxtEstado.setSelectedItem(fis.getEstado());
        TxtComplemento.setText(fis.getComplemento());

        //user = funcionario.getNome();
    }//GEN-LAST:event_jButtonPesquisaridActionPerformed

    private void Tabela_FuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_FuncionarioMouseClicked
        int i = 0;
        Tabela_Funcionario.getModel();
        TxtID.setText(modelo.getValueAt(Tabela_Funcionario.getSelectedRow(), 0).toString());
        try {
            Campos(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,true, true, true, true);
            Botão(false, true, true, true, false, true, true);
            fis = fis_dao.buscaFicicaID(Integer.parseInt(TxtID.getText()));

            cbStatusFis.setSelectedItem(fis.getStatus());
            TxtMatricula.setText(fis.getMatricula());
            TxNome.setText(fis.getNome());
            TxtApelido.setText(fis.getApelido());
            cbEstadoCivil.setSelectedItem(fis.getEstadoCivil());
            txData.setText(sdf.format(fis.getDtNasc()));
            cbSexo.setSelectedItem(fis.getSexo());
            TxCPF.setText(fis.getCPF());
            TxRG.setText(fis.getRG());
            TxtTelefone1.setText(fis.getTelefone());
            TxtCelular.setText(fis.getCelular());
            txEmail.setText(fis.getEmail());
            TxtBairro.setText(fis.getBairro());
            TxtRua.setText(fis.getRua());
            TxtNumero.setText(fis.getNumero());
            TxtCidade.setText(fis.getCidade());
            TxCEP.setText(fis.getCep());
            TxtEstado.setSelectedItem(fis.getEstado());
            TxtComplemento.setText(fis.getComplemento());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Tabela_FuncionarioMouseClicked

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair?") == 0)
        {
            this.dispose();
        }
    }//GEN-LAST:event_ButtonSairActionPerformed
             //---------------------Fomataçao das tabelas--------------------------
    String tituloColuna[] = {"ID", "Matricula", "Nome", "Celular", "Email"};
    public void modeloDATabela(String[][] a){
            modelo.setDataVector(a, tituloColuna);
            Tabela_Funcionario.setModel(new DefaultTableModel(a,tituloColuna){
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
            });
            Tabela_Funcionario.getColumnModel().getColumn(0).setPreferredWidth(30);
            Tabela_Funcionario.getColumnModel().getColumn(1).setPreferredWidth(70);
            Tabela_Funcionario.getColumnModel().getColumn(2).setPreferredWidth(200);
            Tabela_Funcionario.getColumnModel().getColumn(3).setPreferredWidth(100);
            Tabela_Funcionario.getColumnModel().getColumn(4).setPreferredWidth(100);
            DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);            
            Tabela_Funcionario.getColumnModel().getColumn(0).setCellRenderer(centralizado);            
            Tabela_Funcionario.setRowHeight(25);               
    } 
    
    
    
    public void atualizarTabela(){
        fis = new ClienteFisico();
        try {
            fisicos = fis_dao.todosFisicos();
            String dados[][] = new String[fisicos.size()][10];
            int i = 0;
            for (ClienteFisico u : fisicos) {
                dados[i][0] = String.valueOf(u.getId());
                dados[i][1] = u.getMatricula();
                dados[i][2] = u.getNome();
                dados[i][3] = u.getCelular();
                dados[i][4] = u.getEmail(); 
                i++;
            }
            modeloDATabela(dados);
            Tabela_Funcionario.updateUI();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSair;
    private javax.swing.JTable Tabela_Funcionario;
    private javax.swing.JFormattedTextField TxCEP;
    private javax.swing.JTextField TxCPF;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxRG;
    private javax.swing.JTextField TxtApelido;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JFormattedTextField TxtCelular;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JComboBox<String> TxtEstado;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtMatricula;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtRua;
    private javax.swing.JFormattedTextField TxtTelefone1;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbStatusFis;
    private javax.swing.JButton jButtonPesquisarid;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFisica;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txData;
    private javax.swing.JTextField txEmail;
    // End of variables declaration//GEN-END:variables
}
